- name: Check if directory exists
  ansible.builtin.include_role: 
    name: ensure-oakestra-repo-is-cloned
  vars:
    repo: "{{ oak_repo_link }}"
    path: "{{ oak_repo_path }}"
    branch: "{{ oak_repo_version }}"

- name: Check if Go is installed
  ansible.builtin.include_role: 
    name: gantsign.golang
  vars:
    golang_version: '1.22.0'

- name: Install go dependencies
  shell: "cd {{ oak_repo_path }}/go_node_engine && /usr/local/go/bin/go get -u"
  ignore_errors: yes

- name: Build Node Engine 
  shell: "cd {{ oak_repo_path }}/go_node_engine && /usr/local/go/bin/go build -o /bin/NodeEngine NodeEngine.go"
  become: true