- name: Run Root and Cluster Components in 1-DOC mode 
  environment:
    CLUSTER_NAME: '{{ clusterName }}'
    CLUSTER_LOCATION: '{{ clusterLocation }}'
    SYSTEM_MANAGER_URL: '{{ rootIP }}'  
  shell: "cd {{ oak_repo_path }} && nohup docker compose -f run-a-cluster/1-DOC.yaml {{ params }} up --detach"
  become: True