- hosts: one_doc
  tasks:
    - name: Kill One-DOC components
      shell: "docker compose -f {{ repo_path }}/run-a-cluster/1-DOC.yaml kill"
      become: True

- hosts: root
  tasks:
    - name: Kill Root components
      shell: "docker compose -f {{ repo_path }}/root_orchestrator/docker-compose.yml kill"
      become: True

- hosts: clusters
  tasks:
    - name: Kill Cluster components
      shell: "docker compose -f {{ repo_path }}/cluster_orchestrator/docker-compose.yml  kill"
      become: True
