- hosts: nodes

  roles:
    - kill-all-workers

  tasks:
    - name: Restart Net Manager
      shell: nohup NetManager -p 6000 </dev/null >/tmp/netmanager.log 2>&1 &
      become: true

    - name: Restart Node Engine
      environment:
        CLUSTER_IP: '{{ clusterIP }}'
      shell: nohup NodeEngine -n 6000 -a $CLUSTER_IP -p 10100 </dev/null >/tmp/nodeengine.log 2>&1 &
      become: true
