- hosts: nodes

  roles:
    - kill-all-workers

  tasks:

    - name: Restart Node Engine
      environment:
        CLUSTER_IP: '{{ clusterIP }}'
      shell: 'nohup /bin/NodeEngine -a $CLUSTER_IP {{ additionalNodeEngineParams }} -d'
      become: true
      when:  not ( proxy | default(false) )
