- hosts: root
  tasks:

    - name: Clone Oak Repo
      shell: git clone https://github.com/oakestra/oakestra.git
      ignore_errors: true

    - name: Run Root Components
      become: true
      environment:
        SYSTEM_MANAGER_URL: '{{ rootIP }}'  
      shell: cd oakestra/root_orchestrator && nohup docker compose up --build --detach

- hosts: cluster
  tasks:

    - name: Clone Oak Repo
      shell: git clone https://github.com/oakestra/oakestra.git
      ignore_errors: true

    - name: Run Cluster Components
      become: true
      environment:
        SYSTEM_MANAGER_URL: '{{ rootIP }}'
        CLUSTER_NAME: '{{ clusterName }}'
        CLUSTER_LOCATION: '{{ clusterLocation }}'
      shell: cd oakestra/cluster_orchestrator && nohup docker compose up --build --detach  

