- hosts: root
  roles:
    - ensure-oakestra-repo-is-cloned
  tasks:
    - name: Run Root Components
      environment:
        SYSTEM_MANAGER_URL: '{{ rootIP }}'  
      shell: cd  {{ repo_path }}/root_orchestrator ; docker compose up --build --detach
      become: True

- hosts: clusters
  roles:
    - ensure-oakestra-repo-is-cloned
  tasks:
    - name: Run Cluster Components
      environment:
        SYSTEM_MANAGER_URL: '{{ rootIP }}'
        CLUSTER_NAME: '{{ clusterName }}'
        CLUSTER_LOCATION: '{{ clusterLocation }}'
      shell: cd  {{ repo_path }}/cluster_orchestrator ; docker compose up --build --detach  
      become: True

