- hosts: root
  tasks:

  - import_tasks: tasks/clone.yml
    vars:
      repo: https://github.com/oakestra/oakestra.git
      branch: 'develop'
    ignore_errors: yes

  - import_tasks: tasks/start-1doc.yml