oak_repo_path: "{{ ansible_user_dir }}/oakestra_ansible"
oak_repo_link: "https://github.com/oakestra/oakestra"
oak_repo_version: "develop"
oak_net_repo_path: "{{ ansible_user_dir }}/oakestra_net_ansible"
oak_net_repo_link: "https://github.com/oakestra/oakestra-net"
oak_net_repo_version: "develop"